"""empty message

Revision ID: 33873c797583
Revises: 6f0566bc094f
Create Date: 2021-02-12 13:17:10.876666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33873c797583'
down_revision = '6f0566bc094f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
