"""empty message

Revision ID: 402fbee303e5
Revises: 9795eb324769
Create Date: 2021-02-18 22:00:54.942448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402fbee303e5'
down_revision = '9795eb324769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_company',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id_'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_company')
    # ### end Alembic commands ###
