"""empty message

Revision ID: 968677ffc174
Revises: 33873c797583
Create Date: 2021-02-17 17:36:09.116150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '968677ffc174'
down_revision = '33873c797583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_scope',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id_'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scope.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_user_role_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'user_role_id')
    op.drop_table('user_role_scope')
    op.drop_table('user_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_user_role_id_fkey', 'user', 'user_role', ['user_role_id'], ['id_'])
    op.drop_column('user', 'role_id')
    op.create_table('user_role',
    sa.Column('id_', sa.INTEGER(), server_default=sa.text("nextval('user_role_id__seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_', name='user_role_pkey'),
    sa.UniqueConstraint('name', name='user_role_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_role_scope',
    sa.Column('id_', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scope_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scope.id_'], name='user_role_scope_scope_id_fkey'),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_role.id_'], name='user_role_scope_user_role_id_fkey'),
    sa.PrimaryKeyConstraint('id_', name='user_role_scope_pkey')
    )
    op.drop_table('role_scope')
    op.drop_table('role')
    # ### end Alembic commands ###
