"""empty message

Revision ID: 9795eb324769
Revises: 8423f1d7cb04
Create Date: 2021-02-18 19:54:48.424808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9795eb324769'
down_revision = '8423f1d7cb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'namess')
    op.drop_column('company', 'names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('names', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('namess', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
