"""empty message

Revision ID: b587bb362de3
Revises: 
Create Date: 2021-02-08 14:50:31.461470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b587bb362de3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('token')
    )
    op.create_table('company',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('contact_channel',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('user',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('email')
    )
    op.create_table('receiver',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_channel_id', sa.Integer(), nullable=False),
    sa.Column('contact_channel_description', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('zipcode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['contact_channel_id'], ['contact_channel.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('feeling',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internal_uuid', sa.String(length=36), nullable=False),
    sa.Column('external_uuid', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('has_seen', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id_'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id_'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['receiver.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('feeling_file',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('feeling_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feeling_id'], ['feeling.internal_uuid'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeling_file')
    op.drop_table('feeling')
    op.drop_table('receiver')
    op.drop_table('user')
    op.drop_table('contact_channel')
    op.drop_table('company')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
